// Generated by wasm-build.sh. The service worker imports it so that rebuilding the WASM module
// counts as a worker update.
export const WASM_SHA256 = '67f7eb71dc4fccd474d5cbd684267ab99f985c6c5ce123441a65e51cdcdc24cc';
