// Generated by wasm-build.sh. The service worker imports it so that rebuilding the WASM module
// counts as a worker update.
export const WASM_SHA256 = 'f1d59710ee17a862e6e1a9dc120b913c25a32813f89d9a29b12ee9357a9c6c71';
