#!/bin/bash

# Calculate hash of all .rs files in src/
SRC_HASH=$(find src -name "*.rs" -type f -exec sha256sum {} \; | sort | sha256sum | cut -d' ' -f1)

# Read existing hash if build_info.rs exists
if [ -f src/build_info.rs ]; then
    OLD_HASH=$(grep "BUILD_HASH" src/build_info.rs | cut -d'"' -f2)
else
    OLD_HASH=""
fi

# Only update if hash changed or file doesn't exist
if [ "$SRC_HASH" != "$OLD_HASH" ]; then
    echo "Source files changed, updating build info..."
    TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    cat > src/build_info.rs << EOF
// Generated by generate-build-info.sh
pub const BUILD_DATETIME: &str = "$TIMESTAMP";
pub const BUILD_HASH: &str = "$SRC_HASH";
EOF
    echo "Build info updated with timestamp: $TIMESTAMP"
    echo "Source hash: $SRC_HASH"
else
    echo "No source changes detected, build info unchanged"
fi 