#!/bin/bash
set -euo pipefail

# wasm-bindgen-cli must match the wasm-bindgen crate version or the generated
# bindings will fail to load at runtime.
WASM_BINDGEN_VERSION="0.2.100"
TARGET="wasm32-unknown-unknown"

# Prefer the rustup-managed toolchain. On machines where mise or Homebrew put a
# different rustc first on PATH, that rustc often lacks the wasm32 std and the
# build fails with "can't find crate for `core`". `rustup which` resolves the
# real toolchain binaries regardless of PATH shadowing.
if command -v rustup >/dev/null 2>&1; then
    RUSTC_BIN="$(rustup which rustc)"
    CARGO_BIN="$(rustup which cargo)"
else
    RUSTC_BIN="$(command -v rustc)"
    CARGO_BIN="$(command -v cargo)"
fi

./generate-build-info.sh

if command -v rustup >/dev/null 2>&1; then
    rustup target add "$TARGET"
fi

# Only (re)install the CLI when it is missing or the version drifts from the
# crate; `cargo install` otherwise re-downloads and recompiles on every build.
if ! command -v wasm-bindgen >/dev/null 2>&1 || \
   [ "$(wasm-bindgen --version | awk '{print $2}')" != "$WASM_BINDGEN_VERSION" ]; then
    "$CARGO_BIN" install wasm-bindgen-cli --version "$WASM_BINDGEN_VERSION"
fi

# Panic messages carry source paths, which would otherwise put this machine's home directory (and
# username) into the published module for every dependency.
CARGO_HOME_DIR="${CARGO_HOME:-$HOME/.cargo}"
RUSTC="$RUSTC_BIN" "$CARGO_BIN" build --target "$TARGET" --release \
    --config "target.$TARGET.rustflags=['--remap-path-prefix=$CARGO_HOME_DIR=/cargo', '--remap-path-prefix=$PWD=/build']"

# Respect CARGO_TARGET_DIR when set (e.g. sandboxed/CI builds redirect it).
TARGET_DIR="${CARGO_TARGET_DIR:-target}"
WASM_ARTIFACT="$TARGET_DIR/$TARGET/release/mcp_browser_client.wasm"

wasm-bindgen --target no-modules --out-dir public "$WASM_ARTIFACT"

# The service worker imports build.js, so a new module changes one of the worker's scripts and
# browsers install the new worker, and with it the new module, on the next reload.
WASM_SHA256="$(sha256sum public/mcp_browser_client_bg.wasm | cut -d' ' -f1)"
cat > public/build.js << EOF
// Generated by wasm-build.sh. The service worker imports it so that rebuilding the WASM module
// counts as a worker update.
export const WASM_SHA256 = '$WASM_SHA256';
EOF

echo "Build complete: public/mcp_browser_client_bg.wasm (sha256 ${WASM_SHA256:0:12})"
