#!/usr/bin/env node
// Bundles sdk-client/ with @modelcontextprotocol/client into public/sdk_client.js and writes
// public/build-sdk.js with the bundle's hash and size. The bundle is a script, not a module:
// service workers can't import() on demand, so public/mcp-clients.js fetches and evaluates it, and
// it sets self.mcpSdkClient.
//
//   node sdk-client/build.mjs    (npm run build:sdk)

import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(root, 'sdk-client');
const readJson = path => JSON.parse(readFileSync(join(root, path), 'utf8'));
const app = readJson('package.json');
const sdk = readJson('node_modules/@modelcontextprotocol/client/package.json');

const sourceHash = createHash('sha256');
for (const name of readdirSync(source).filter(name => name.endsWith('.js')).sort()) {
    sourceHash.update(readFileSync(join(source, name)));
}
sourceHash.update(sdk.version);

const outfile = join(root, 'public', 'sdk_client.js');
await build({
    entryPoints: [join(source, 'index.js')],
    outfile,
    bundle: true,
    format: 'iife',
    globalName: 'mcpSdkClient',
    footer: { js: 'self.mcpSdkClient = mcpSdkClient;' },
    // The browser conditions pick the SDK's browser shims (its CORS handling and JSON Schema
    // validator).
    platform: 'browser',
    target: 'es2022',
    minify: true,
    sourcemap: true,
    logLevel: 'warning',
    define: {
        __CLIENT_VERSION__: JSON.stringify(app.version),
        __SDK_VERSION__: JSON.stringify(sdk.version),
        __BUILD_TIME__: JSON.stringify(new Date().toISOString().replace(/\.\d+Z$/, 'Z')),
        __SOURCE_HASH__: JSON.stringify(sourceHash.digest('hex')),
    },
});

const bundle = readFileSync(outfile);
const sha256 = createHash('sha256').update(bundle).digest('hex');
writeFileSync(join(root, 'public', 'build-sdk.js'), `// Generated by sdk-client/build.mjs. The service worker imports it, so rebuilding the SDK client
// counts as a worker update.
export const SDK_SHA256 = '${sha256}';
export const SDK_BYTES = ${bundle.length};
`);
console.log(`Built public/sdk_client.js (${(bundle.length / 1024).toFixed(1)} KB, sha256 ${sha256.slice(0, 12)}) on @modelcontextprotocol/client ${sdk.version}`);
