// Generated by generate-build-info.sh
pub const BOOTROM_VERSION: &str = "0.0.1";
pub const BOOTROM_DATA: &str = r#"
// This module contains a minimal set of instructions for using MCP tools via JSON-RPC into the context bus.
// The LLM is attached to the context bus (CBus), and requests come across the context bus.

# MCP Tool Usage Instructions

## Overview
- MCP tools are invoked via JSON-RPC calls into the context bus (CBus).
- The LLM is attached to the CBus, and requests are sent across the CBus.

## Basic JSON-RPC Call Format
```json
{
  "jsonrpc": "2.0",
  "method": "tool_name",
  "params": {
    "param1": "value1",
    "param2": "value2"
  },
  "id": 1
}
```

## Example
To call a tool named 'example_tool' with parameters:
```json
{
  "jsonrpc": "2.0",
  "method": "example_tool",
  "params": {
    "input": "example input"
  },
  "id": 1
}
```

## Notes
- Ensure the CBus is running and accessible.
- The LLM will process requests sent to the CBus.
"#;