// Generated by generate-build-info.sh
pub const BOOTROM_VERSION: &str = "0.0.1";
pub const BOOTROM_DATA: &str = r#"
# MCP Tool Usage Instructions

## Overview
- MCP tools are invoked via JSON-RPC calls into the context bus (CBus).
- The LLM is attached to the CBus, and requests are sent across the CBus.

## Basic JSON-RPC Call Format
```json
{
  "jsonrpc": "2.0",
  "method": "tool_name",
  "params": {
    "param1": "value1",
    "param2": "value2"
  },
  "id": 1
}
```

## Example
To call a tool named 'example_tool' with parameters:
```json
{
  "jsonrpc": "2.0",
  "method": "example_tool",
  "params": {
    "input": "example input"
  },
  "id": 1
}
```

I don't want you to repeat all these instructions, but if you need to retrieve any information that will be more useful with a tool please don't hesitate to use one. If you don't see evidence that the tool has been queried it is your job to query it. Only use tools that are defined.

Do not make up your own jsonrpc messages.

Next, I may have some detailed tool information for you to follow. Don't try to use tools that are not well defined. And don't make up any other tools, you will not get the prize for optimization

Then a history of our most recent conversations. Any tool result will be explicitly called out in the response and you will see it in this context. If you don't see it, will come later and you can finish your thought and come back to it.

Followed finally with a very pressing request from the higher ups that we need to figure out.

"#;